name: Apply commit on Hawthorne

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  git_pull:
    runs-on: self-hosted  # Use your self-hosted runner label here

    steps:
      - name: Run git pull
        working-directory: /data/ewww/enstrayedcom  # Specify the directory
        run: |
          git pull
