name: Apply commit on Hawthorne
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Pull changes from GitHub
        working-directory: /data/ewww/enstrayedcom  # Specify the directory
        run: |
          git pull
